### ISSUE TITLE
The UTC representation of the date falls outside the year range 1-9999.

### ISSUE THREAD

**Issue by jrouaix** [joancaron/cryptocompare-api#10]
Tried to consume the Cardano snapshot full : https://www.cryptocompare.com/api/data/coinsnapshotfullbyid?id=321992

The value : "StartDate":"01/01/0001" is not handled by the deserialization.

**Comment by joancaron** [comment]
Fixed here : https://github.com/joancaron/cryptocompare-api/commit/e06323bce9c945827d642749e838024e31d94fb2
