### ISSUE TITLE
Boolean Values Not Working

### ISSUE THREAD

**Issue by pcartwright81** [joancaron/cryptocompare-api#28]
When running the history client I noticed that I was getting an exception that said alldata was not a boolean value.  What I noticted was bool?.ToString() was True.  Added ToLower() and the parameter is now valid. I also got exceptions when testing other parameters on the same method also.

**Comment by joancaron** [comment]
Hello,
Thanks for reporting this issue, that's a good catch 
It seems that all boolean values must ne lowered... I'll fix this soon
Thanks you again
