### ISSUE TITLE
Multiple Symbols Full Data

### ISSUE THREAD

**Issue by arrebagrove** [joancaron/cryptocompare-api#41]
# ✨ Feature request

The Multiple Symbols Full Data Api  return object (CoinFullAggregatedDataDisplay) is missing some members like

- VolumeHour
- VolumeHourTo
- OpenHour
- OpenHourTo
- LowHour
- ImageUrl

Can you include them.

**Comment by joancaron** [comment]
Hello @arrebagrove, I'll include these changes soon on the next release thanks for this request!
