### ISSUE TITLE
That's not quite clear what does the library actually do.

### ISSUE THREAD

**Issue by agat366** [joancaron/cryptocompare-api#47]
Hi!

Could you clarify (and possibly add more description to read.me file if you want) what is actually the purpose of the library. It's not quite clear what should it compare, compare to what and what are the sources of the data.

Thanks!

**Comment by joancaron** [comment]
Hello @agat366 ,
As written at the first line of the read me file, this project is:
> An async-based CryptoCompare API client library for .NET and .NET Core

All methods of this client call CryptoCompare api endpoints 
You can find more details here : https://min-api.cryptocompare.com/
