### ISSUE TITLE
Json UnixTime Conversion Error

### ISSUE THREAD

**Issue by Bcantz27** [joancaron/cryptocompare-api#8]
I am getting an exception when called a SnapShotFullAsync on coin Id 33639 and a few others

This is the line of code im calling that triggeres the exception 
`CryptoCompare.CoinSnapshotFullData coinInfo = CryptoCompareClient.Instance.Coins.SnapshotFullAsync(33639).Result.Data;`

The exception has to do with the UnixTimeConverter.
Here is the full exception: 
![error](https://user-images.githubusercontent.com/1483804/35190961-e2729140-fe3c-11e7-97b7-93d77d5fd40d.JPG)

![error2](https://user-images.githubusercontent.com/1483804/35190978-612e74ae-fe3d-11e7-9d2b-18fca9384011.JPG)

**Comment by joancaron** [comment]
Fixed here : https://github.com/joancaron/cryptocompare-api/commit/e06323bce9c945827d642749e838024e31d94fb2
